### ISSUE TITLE
Refresh แล้ววิ่งแซงพี่ตูน

### ISSUE THREAD

**Issue by ttamsare** [teerasej/run-with-p-toon#1]
**สิ่งที่ควรเป็น**

Refresh หน้าวิ่งแล้ว ความเร็วสัมพันธ์ค่ากับที่เลือกไว้

**สิ่งที่เกิดขึ้น**

เลือกวิ่งช้าๆ แต่ความเร็วแซงพี่ตูน

**ขั้นตอนที่ทำให้เกิดข้อผิดพลาด**

1. เปิดเข้ามาหน้าวิ่ง
2. กดRefresh

**link ภาพประกอบ**
https://ibb.co/nzaFF6

**เว็บเบราเซอร์และรุ่นที่ใช้**

Google Chrome 64

**Comment by teerasej** [comment]
เทียบยังไงว่าแซงพี่ตูนแล้ว

**Comment by ttamsare** [comment]
เพราะตอนนี้พี่ตูนป่วย เลยวิ่งแซง
เลือกวิ่งช้าๆ ความเร็วอยู่5-7 ก้าว/s อันนี้ไป24 ก้าว/s

**Comment by teerasej** [comment]
เข้าใจแล้ว กำลังตรวจสอบให้

**Comment by teerasej** [comment]
ตรวจเจอแล้ว แก้ใน 0.9.1

**Comment by ttamsare** [comment]
ยังเป็นอยู่นะ 0.9.2

**Comment by teerasej** [comment]
รับทราบปัญหาใน 0.9.2

**Comment by teerasej** [comment]
แก้และทดสอบอีกครั้งแล้ว 

เป็น bug ในเคสสำหรับนักวิ่งที่ login facebook แล้ว 
แก้ใน 0.9.4
