### ISSUE TITLE
Login Facebook ค้าง

### ISSUE THREAD

**Issue by ttamsare** [teerasej/run-with-p-toon#2]
**สิ่งที่ควรเป็น**

Login Facebook แล้วขึ้นชื่อUserเลย

**สิ่งที่เกิดขึ้น**

กดปุ่ม Log in ด้วย Facebook แล้วค้าง ต้องRefreshถึงข้อมูลจะขึ้น

**ขั้นตอนที่ทำให้เกิดข้อผิดพลาด**

1. เปิดเข้ามาหน้าแรก
2. เลือก Login ด้วยFacebook
3. ทำตามขั้นตอน Login

link ภาพประกอบ
-

เว็บเบราเซอร์และรุ่นที่ใช้

Google Chrome 64

**Comment by teerasej** [comment]
เจอปัญหาแล้ว เดี๋ยวแก้ไขก่อน
ต้องให้อู่ลอง deploy แล้ว เข้าไปทดสอบอีกที

**Comment by teerasej** [comment]
อู่ deploy 0.9.3 แล้ว 

สามารถ login และแสดงชื่อได้ตามปกติ 

ติดกรณีหนึ่ง คือถ้า Web Browser มัน block pop up ตัว Web Browser จะแจ้งเตือน 
คนเข้าเว็บต้องอนุญาตให้แสดง pop up และกด login ใหม่ ก็จะทำงานได้ตามปกติ

จากการหาข้อมูลขั้นตอนนี้เป็นขั้นตอนปกติ ที่เจ้าของเครื่องจะตั้งให้ block pop up หรือไม่ก็ได้ 
แต่จะลองดูว่าจะลัดขั้นตอนนี้ได้ไหม

**Comment by teerasej** [comment]
ลองปรับ code แล้ว เดี๋ยวส่งให้อู่ deploy 0.9.4
