### ISSUE TITLE
Miner ไม่ทำงานในหน้าวิ่ง ถ้าไม่ได้ login FB

### ISSUE THREAD

**Issue by teerasej** [teerasej/run-with-p-toon#4]
**สิ่งที่ควรเป็น**

miner ในหน้าวิ่ง ควรเริ่มการทำงานแม้ว่าจะไม่ได้ login ด้วย FB

**สิ่งที่เกิดขึ้น**

miner หยุดการทำงานในหน้าวิ่ง ในกรณีที่ไม่ได้ login FB และกดเข้ามาวิ่งเลย

**ขั้นตอนที่ทำให้เกิดข้อผิดพลาด**

1. เปิดเข้ามาที่หน้าแรก
2. กด "วิ่งเลย"
3. เข้ามาในหน้าวิ่ง
4. miner ไม่ทำงาน ไม่มีข้อมูลการวิ่งของนักวิ่งแสดงในสถิติ

**link ภาพประกอบ**
ไม่มี

**เว็บเบราเซอร์และรุ่นที่ใช้**

Google Chrome 64

**Comment by teerasej** [comment]
สาเหตุเกิดจากสั่งหยุดการทำงานของ miner โดยตรงในหน้าวิ่ง

แก้ไขใน 0.9.4

**Comment by ttamsare** [comment]
log in แล้วพอกดมาหน้าวิ่ง บางทีก็ไม่วิ่งนะ ทั้งๆที่default คือ วิ่งเบาๆ ป่ะ

**Comment by teerasej** [comment]
อาการที่ว่าไม่วิ่ง คือสถานะตัวเลขส่วนนี้ไม่ขึ้นป่ะ? 

<a href="https://ibb.co/dmKnV6"><img src="https://preview.ibb.co/iJ6Cxm/Screen_Shot_2017_11_21_at_23_22_47.png" alt="Screen_Shot_2017_11_21_at_23_22_47" border="0"></a>

ถ้าใช่ อันนี้ขึ้นอยู่กับทาง coinhive.js แล้ว เพราะจาก log miner ทำงานตามปกติ

<a href="https://ibb.co/nNB9A6"><img src="https://preview.ibb.co/jdQEcm/Screen_Shot_2017_11_21_at_23_24_15.png" alt="Screen_Shot_2017_11_21_at_23_24_15" border="0"></a>

ตอนเข้ามาหน้า run.html ลองคลิกขวา แล้วเข้าไปดู log ในโหมด inspect ดู ว่ามันทำงานเหมือนกันหรือเปล่า

<a href="https://imgbb.com/"><img src="https://image.ibb.co/diBsV6/2017_11_21_23_26_44.png" alt="2017_11_21_23_26_44" border="0"></a>

**Comment by ttamsare** [comment]
ใช่ ขึ้นเป็น 0 หมดเลย

**Comment by teerasej** [comment]
ลองดู log ตามวิธีที่กูแปะภาพให้ ดูว่า log ขึ้นมาคล้ายกันหรือเปล่า 

ส่วนเคยเจอครั้งเดียวเมื่อตอนทำแรกๆ เลย เหมือน coinhive ไม่คืนค่ากลับมา

**Comment by teerasej** [comment]
คุยกับอู่ และเค บอกว่าเจอบ้าง ไม่เจอบ้าง 
ปัจจุบันยัง reproduce ไม่ได้
