### ISSUE TITLE
โยน public_profile ของ facebook มาแทน UserID

### ISSUE THREAD

**Issue by paponyon** [teerasej/run-with-p-toon#8]
ให้ Front เรียก Graph API ตามด้านล่าง แล้วส่งก้อน response แบบนี้มาตอนเรียกเส้น  regisRunner

**Facebook Graph API call:** 
&nbsp;&nbsp;&nbsp;me?fields=id,name,age_range,gender,picture

**Facebook Graph response format:**
{
  "id": "993857387299671",
  "name": "Papon Yongpisanpop",
  "age_range": {
    "min": 21
  },
  "gender": "male",
  "picture": {
    "data": {
      "height": 50,
      "is_silhouette": false,
      "url": "https://scontent.xx.fbcdn.net/v/t1.0-1/p50x50/22730457_1700746019944134_5119059062968151632_n.jpg?oh=679a23fe56182cadc8b0116e58b222f9&oe=5A9E5778",
      "width": 50
    }
  }
}

**Comment by teerasej** [comment]
implement ใน 0.9.8
รอการทดสอบบน dev server แล้วค่อยปิด

**Comment by paponyon** [comment]
@teerasej ทดสอบแล้ว เอาขึ้น production เรียบร้อย ปิดได้เลย

**Comment by teerasej** [comment]
ยืนยัน ปิด issue
ถ้าอันไหนทดสอบผ่านแล้วกดปิดได้เลยเน้อ
